services:
  app:
    build: .
    container_name: tutorias_app
    restart: always
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_USER: root
      MYSQL_PASSWORD: 2004
    ports:
      - "8080:8080"
    volumes:
      - C:/tutorias:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  uploads_data: